name: "OCI Terraform"
description: "A simple action executing Terraform code (init, plan, apply, destroy)"
author: lhotakj
branding:
  icon: hard-drive
  color: purple

inputs:
  terraform-version: # id of input
    description: 'Target version of Terraform, by default uses the latest'
    required: false
    default: 'latest'
  private_key:
    description: 'Content of the private key'
    required: true
  private_key_password:
    description: 'Private key password'
    required: false
  fingerprint:
    description: 'Fingerprint of your private key'
    required: true

runs:
  using: "composite"
  steps:
    - name: "Install Terraform ${{ inputs.version }}"
      shell: bash
      run: |
        TERRAFORM_VERSION=`curl -sL https://releases.hashicorp.com/terraform/index.json | jq -r '.versions[].builds[].url' | egrep -v 'rc|beta|alpha' | egrep 'linux.*amd64' | tail -1`
        wget -q https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip
        unzip terraform_${TERRAFORM_VERSION}_linux_amd64.zip
        rm terraform_${TERRAFORM_VERSION}_linux_amd64.zip
        echo $TERRAFORM_VERSION
        terraform -v

    - name: "Prepare secrets"
      shell: bash
      run: |
        echo ":: Running INIT"
        IFS=
        echo ":: Preparing secrets"
        export TF_VAR_PRIVATE_KEY="${{ inputs.private_key }}"
        export TF_VAR_PRIVATE_KEY_PASSWORD="${{ inputs.private_key_password }}"
        export TF_VAR_FINGERPRINT="${{ inputs.private_key_fingerprint }}"
        echo ":: Injecting secrets"
        eval "IFS=\"\n\"; echo \"$(<terraform/secrets_override.yaml)\"" > terraform/secrets_override.yaml

    - name: "Checkout"
      uses: "actions/checkout@master"
