name: "OCI Terraform - output"
description: "A simple action executing Terraform code = output"
author: lhotakj
branding:
  icon: hard-drive
  color: purple

inputs:
  context:
    description: 'Folder with terraform code'
    required: false
    default: '.'

runs:
  using: "composite"
  steps:
    - name: "Get Terraform environment file"
      uses: actions/download-artifact@v3
      with:
        name: ".github_env"
        path: ${{ inputs.context }}/.github_env
        
    - name: "Run terraform plan"
      working-directory: ${{ inputs.context }}
      shell: bash
      run: |        
        source ./github_env
        terraform plan
