name: "OCI Terraform - output"
description: "A simple action executing Terraform code = output"
author: lhotakj
branding:
  icon: hard-drive
  color: purple

inputs:
  context:
    description: 'Folder with terraform code'
    required: false
    default: '.'
  compartment_ocid:
    description: 'Compartment OID'
    required: true

runs:
  using: "composite"
  steps:
    - name: "Run terraform plan"
      working-directory: ${{ inputs.context }}
      shell: bash
      run: |        
        export TF_VAR_compartment_ocid=${{ inputs.compartment_ocid }}
        terraform plan
