name: "OCI Terraform - plan"
description: "A simple action executing Terraform code = plan"
author: lhotakj
branding:
  icon: hard-drive
  color: purple

inputs:
  context:
    description: 'Folder with terraform code'
    required: false
    default: '.'

runs:
  using: "composite"
  steps:

    - name: "Run terraform plan"
      working-directory: ${{ inputs.context }}
      shell: bash
      run: |
        source ${GH_ENV_FILE}
        terraform plan

    - name: "Cleanup of secrets on failure"
      if: failure()
      shell: bash
      run: |
        echo "::debug::Cleanup secrets"
        rm -rf ~/.ssh/id_rsa
        rm -rf ~/.ssh/id_rsa.pub
