name: "OCI Terraform - apply"
description: "A simple action executing Terraform code = apply"
author: lhotakj
branding:
  icon: hard-drive
  color: purple

inputs:
  context:
    description: 'Folder with terraform code'
    required: false
    default: '.'

outputs:
  output_json:
    description: 'Terraform output in JSON format'
    value: ${{ steps.apply.outputs.output_json }}

runs:
  using: "composite"
  steps:
    - name: "Run terraform apply"
      id: "apply"
      working-directory: ${{ inputs.context }}
      shell: bash
      run: |
        source ${GH_ENV_FILE}
        terraform apply -auto-approve
        echo "::debug::Saving the Terraform output in JSON format"
        TERRAFORM_JSON_OUTPUT=$(terraform output -json)
        TERRAFORM_JSON_OUTPUT="${TERRAFORM_JSON_OUTPUT//'%'/'%25'}"
        TERRAFORM_JSON_OUTPUT="${TERRAFORM_JSON_OUTPUT//$'\n'/'%0A'}"
        TERRAFORM_JSON_OUTPUT="${TERRAFORM_JSON_OUTPUT//$'\r'/'%0D'}"
        echo "output_json=$TERRAFORM_JSON_OUTPUT" >> $GITHUB_OUTPUT

    - name: "Cleanup of secrets"
      if: failure()
      shell: bash
      run: |
        echo "::debug::Cleanup secrets"
        rm -rf ~/.ssh/id_rsa
        rm -rf ~/.ssh/id_rsa.pub
