name: "OCI Terraform - apply"
description: "A simple action executing Terraform code = apply"
author: lhotakj
branding:
  icon: hard-drive
  color: purple

inputs:
  context:
    description: 'Folder with terraform code'
    required: false
    default: '.'

runs:
  using: "composite"
  steps:
    - name: "Run terraform apply"
      working-directory: ${{ inputs.context }}
      shell: bash
      run: |
        source ./github_env
        terraform apply -auto-approve
